import React from "react";

export const settings = function (color, backgroundColor) {
  return (
    <React.Fragment>
      <line
        x1="4"
        y1="4"
        x2="4"
        y2="106"
        stroke={color}
        strokeWidth="8"
        strokeLinecap="round"
      />
      <line
        x1="6"
        y1="24"
        x2="106"
        y2="24"
        stroke={color}
        strokeWidth="8"
        strokeLinecap="round"
      />
      <circle
        cx="49"
        cy="23"
        r="10"
        fill={backgroundColor}
        stroke={color}
        strokeWidth="8"
      />
      <line
        x1="6"
        y1="55"
        x2="106"
        y2="55"
        stroke={color}
        strokeWidth="8"
        strokeLinecap="round"
      />
      <circle
        cx="81"
        cy="55"
        r="10"
        fill={backgroundColor}
        stroke={color}
        strokeWidth="8"
      />
      <line
        x1="6"
        y1="86"
        x2="106"
        y2="86"
        stroke={color}
        strokeWidth="8"
        strokeLinecap="round"
      />
      <circle
        cx="30"
        cy="86"
        r="10"
        fill={backgroundColor}
        stroke={color}
        strokeWidth="8"
      />
    </React.Fragment>
  );
};
